drop table users;
create table users(
name varchar(32) NOT NULL,
	password varchar(32) NOT NULL,
	email varchar(255) primary key,
	category varchar(11) not null,
	party_id int(11)  not null,
	hasVoted varchar(8) not null,
	vote_count int(11) not null,
	post_applied varchar(11),
	gender varchar(7) not null,
	address varchar(255) not null,
	approved int(1) default 0,
	quote varchar(255),
	about varchar(255)
);
insert into users values('Mukul Garg',	'abcd@1234',	'admin1010@localohost',	'admin',	'0',	'false',	'0',	 '',	'MALE',	'4415 Burrows Road',	1,	'Streamlined upward-trending extranet',	'Innovative empowering access');
insert into users values('Phil Hannah',	'abcd@1234',	'admin1011@localohost',	'admin',	'0',	'false',	'0',	'',	'female',	'960 Eastlawn Court',	1,	'Down-sized zero tolerance adapter',	'Self-enabling discrete database');
insert into users values('Sajal Garg',	'abcd@1234',	'candidate1@localohost',	'candidate',	'641791',	'false',	'0',	'PRESIDENT',	'MALE',	'8455 Amoth Junction',	1,	'Organized scalable project',	'Cross-group stable software');
insert into users values('Manohar Parrikar',	'abcd@1234',	'candidate2@localohost',	'candidate',	'641791',	'false',	'0',	'V_PRESIDENT',	'MALE',	'086 Shoshone Drive',	1,	'Self-enabling incremental migration',	'Integrated solution-oriented encryption');
insert into users values('Sarthak Sharma',	'abcd@1234',	'candidate3@localohost',	'candidate',	'641791',	'false',	'0',	'SECRETARY',	'MALE',	'67140 Forest Run Avenue',	1,	'Polarised next generation forecast',	'Adaptive upward-trending flexibility');
insert into users values('Tanya Jain',	'abcd@1234',	'candidate4@localohost',	'candidate',	'641791',	'false',	'0',	'J_SECRETARY',	'female',	'8 Chive Trail',	1,	'Persevering client-driven approach',	'Customizable disintermediate alliance');
insert into users values('Samridhi Jain',	'abcd@1234',	'candidate5@localohost',	'candidate',	'641791',	'false',	'0',	'TREASURER',	'female',	'6 Dixon Trail',	1,	'Versatile logistical support',	'Cross-platform next generation process improvement');
insert into users values('Palak Jain',	'abcd@1234',	'candidate6@localohost',	'candidate',	'641800',	'false',	'0',	'PRESIDENT',	'female',	'8413 Waxwing Parkway',	1,	'Enhanced system-worthy strategy',	'Compatible uniform open system');
insert into users values('Sandeep Dhariwal',	'abcd@1234',	'candidate7@localohost',	'candidate',	'641800',	'false',	'0',	'V_PRESIDENT',	'MALE',	'054 Eliot Street',	1,	'Multi-tiered disintermediate website',	'Customizable real-time array');
insert into users values('Saurav Panwar',	'abcd@1234',	'candidate8@localohost',	'candidate',	'641800',	'false',	'0',	'SECRETARY',	'MALE',	'8337 Walton Point',	1,	'Diverse tangible definition',	'Advanced optimizing installation');
insert into users values('Rajeev Sharma',	'abcd@1234',	'candidate9@localohost',	'candidate',	'641800',	'false',	'0',	'J_SECRETARY',	'MALE',	'6 East Crossing',	1,	'Expanded grid-enabled hardware',	'Reduced impactful solution');
insert into users values('Yatika Bhardwaj',	'abcd@1234',	'candidate10@localohost',	'candidate',	'641800',	'false',	'0',	'TREASURER',	'female',	'57928 Hanover Road',	1,	'Re-engineered global infrastructure',	'Grass-roots multi-state migration');
insert into users values('Uday',	'abcd@1234',	'candidate11@localohost',	'candidate',	'641819',	'false',	'0',	'PRESIDENT',	'MALE',	'987 Cardinal Parkway',	1,	'Mandatory zero defect contingency',	'Grass-roots next generation extranet');
insert into users values('Atishay Jain',	'abcd@1234',	'candidate12@localohost',	'candidate',	'641819',	'false',	'0',	'V_PRESIDENT',	'MALE',	'65489 Garrison Park',	1,	'Profit-focused fresh-thinking methodology',	'Persistent coherent initiative');
insert into users values('Navneet Kumar',	'abcd@1234',	'candidate13@localohost',	'candidate',	'641819',	'false',	'0',	'SECRETARY',	'MALE',	'349 Saint Paul Junction',	1,	'Seamless logistical flexibility',	'Multi-lateral high-level initiative');
insert into users values('Deepak Kumar',	'abcd@1234',	'candidate14@localohost',	'candidate',	'641819',	'false',	'0',	'J_SECRETARY',	'MALE',	'066 Oakridge Plaza',	1,	'Face to face zero tolerance website',	'Universal incremental installation');
insert into users values('Ankush Garg',	'abcd@1234',	'candidate15@localohost',	'candidate',	'641819',	'false',	'0',	'TREASURER',	'MALE',	'5207 Sheridan Plaza',	1,	'Profound contextually-based secured line',	'Business-focused 4th generation moderator');
insert into users values('Enrica Dziwisz',	'0OLLee',	'edziwisz0@patch.com',	'student',	'0',	'false',	'0',	'',	'female',	'0959 Crescent Oaks Way',	1,	'Triple-buffered interactive Graphic Interface',	'Horizontal content-based website');
insert into users values('Dani Bladon',	'4J1bsE',	'dbladon1@harvard.edu',	'student',	'0',	'false',	'0',	'',	'MALE',	'883 Veith Hill',	1,	'Decentralized clear-thinking support',	'Ergonomic full-range analyzer');
insert into users values('Daniel Trowell',	'QLwmXRv8',	'dtrowell2@tripadvisor.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'74192 Pine View Junction',	1,	'Optimized intangible hierarchy',	'Centralized solution-oriented projection');
insert into users values('Eileen Cranmor',	'8sXTyIN1Fl',	'ecranmor3@dell.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'12477 Evergreen Hill',	1,	'Enterprise-wide foreground encryption',	'Fundamental cohesive projection');
insert into users values('Harri Shenfish',	'nyccGbh',	'hshenfish4@facebook.com',	'student',	'0',	'false',	'0',	'',	'female',	'051 Burning Wood Crossing',	1,	'Grass-roots intangible analyzer',	'Synergistic local focus group');
insert into users values('Chery Mathissen',	'hJRGWad',	'cmathissen5@csmonitor.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'285 Darwin Place',	1,	'De-engineered coherent software',	'Multi-layered fault-tolerant analyzer');
insert into users values('Chiquita Farndon',	'CLFEd4trwT',	'cfarndon6@mlb.com',	'student',	'0',	'false',	'0',	'',	'female',	'67 Grayhawk Terrace',	1,	'Advanced intangible neural-net',	'Open-architected holistic solution');
insert into users values('Anders Caulfield',	'RUCG2SzhNZ',	'acaulfield7@patch.com',	'student',	'0',	'false',	'0',	'',	'female',	'883 Westend Junction',	1,	'Face to face client-driven hierarchy',	'Focused executive definition');
insert into users values('Rosalind Scoullar',	'dDe82Xa6c7',	'rscoullar8@hugedomains.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'25527 Elka Terrace',	1,	'Function-based multi-state encryption',	'Focused real-time customer loyalty');
insert into users values('Derby Swanger',	'ZrZCD0Mzm8sa',	'dswanger9@altervista.org',	'student',	'0',	'false',	'0',	'',	'female',	'83 Carey Hill',	1,	'Robust uniform instruction set',	'Optional stable Graphical User Interface');
insert into users values('Conrado Sach',	'LCrOcaF6BCF',	'csacha@imdb.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'2 Carey Plaza',	1,	'Right-sized value-added analyzer',	'Phased homogeneous circuit');
insert into users values('Arabelle Haresign',	'cjm4IvUR',	'aharesignb@msn.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'5679 Kinsman Park',	1,	'Optimized motivating monitoring',	'Vision-oriented incremental model');
insert into users values('Gayleen Symon',	'DIWIWVGiAQ6u',	'gsymonc@bizjournals.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'6713 Huxley Plaza',	1,	'Pre-emptive cohesive encoding',	'User-centric clear-thinking solution');
insert into users values('Artus Michallat',	'jVu5jKbVsU',	'amichallatd@shareasale.com',	'student',	'0',	'false',	'0',	'',	'female',	'763 Stoughton Court',	1,	'Profound methodical matrix',	'Devolved optimal service-desk');
insert into users values('Thane McCloy',	'y8mEEeDD',	'tmccloye@soundcloud.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'54 Golf Road',	1,	'Persistent reciprocal info-mediaries',	'Vision-oriented dynamic protocol');
insert into users values('Zacharia Raistrick',	'bY61Eod1e4',	'zraistrickf@geocities.jp',	'student',	'0',	'false',	'0',	'',	'female',	'19565 Almo Park',	1,	'Advanced logistical frame',	'Multi-lateral empowering hierarchy');
insert into users values('Freedman Axcel',	'WbjQYzfpViFU',	'faxcelg@ca.gov',	'student',	'0',	'false',	'0',	'',	'female',	'808 Sachs Park',	1,	'Virtual 24 hour synergy',	'Phased modular artificial intelligence');
insert into users values('Katheryn Gillfillan',	'ardQiAtT',	'kgillfillanh@biglobe.ne.jp',	'student',	'0',	'false',	'0',	'',	'MALE',	'27770 Maple Wood Center',	1,	'Synchronised optimal capacity',	'Advanced client-server archive');
insert into users values('Ariana Aitken',	'5jzdyVUe',	'aaitkeni@xinhuanet.com',	'student',	'0',	'false',	'0',	'',	'female',	'0817 Tennessee Pass',	1,	'Operative methodical initiative',	'Organized needs-based projection');
insert into users values('Gaspar Paunton',	'Ityhu3vY7',	'gpauntonj@kickstarter.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'3 Havey Parkway',	1,	'Balanced mission-critical contingency',	'Inverse 5th generation flexibility');
insert into users values('Boris Jones',	'tdboistI',	'bjonesk@google.ru',	'student',	'0',	'false',	'0',	'',	'MALE',	'3383 Forest Terrace',	1,	'Reverse-engineered methodical architecture',	'Multi-channelled intermediate access');
insert into users values('Orel Landis',	'oNkINTe0Epg',	'olandisl@ihg.com',	'student',	'0',	'false',	'0',	'',	'female',	'6 Grover Park',	1,	'Programmable 6th generation adapter',	'Decentralized background system engine');
insert into users values('Chrissie MacElane',	'Yv5M2bPh',	'cmacelanem@ebay.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'8800 Novick Pass',	1,	'Total dedicated budgetary management',	'Secured even-keeled superstructure');
insert into users values('Sharia Persich',	'NCSO85Vew8e',	'spersichn@state.tx.us',	'student',	'0',	'false',	'0',	'',	'MALE',	'0 Meadow Vale Park',	1,	'Public-key cohesive access',	'Intuitive intangible knowledge base');
insert into users values('Gertrudis Epple',	'EgC295',	'geppleo@europa.eu',	'student',	'0',	'false',	'0',	'',	'MALE',	'6219 Walton Circle',	1,	'Inverse multi-tasking complexity',	'Grass-roots bandwidth-monitored complexity');
insert into users values('Jeth Dolder',	'NrJwx1MbJ',	'jdolderp@ft.com',	'student',	'0',	'false',	'0',	'',	'female',	'0 Petterle Avenue',	1,	'Up-sized context-sensitive utilisation',	'Multi-lateral neutral flexibility');
insert into users values('Emily Chinge de Hals',	'Ai6644vCm',	'echingeq@ow.ly',	'student',	'0',	'false',	'0',	'',	'MALE',	'6 Arkansas Street',	1,	'Configurable explicit architecture',	'Open-source bandwidth-monitored superstructure');
insert into users values('Alexei Pratchett',	'pFe3flVM0397',	'apratchettr@archive.org',	'student',	'0',	'false',	'0',	'',	'female',	'6118 Morningstar Alley',	1,	'Universal bandwidth-monitored ability',	'Reverse-engineered contextually-based process improvement');
insert into users values('Dieter Fleet',	'J7vIjyB88',	'dfleets@facebook.com',	'student',	'0',	'false',	'0',	'',	'female',	'98832 Hudson Plaza',	1,	'Triple-buffered object-oriented workforce',	'Synergized systemic local area network');
insert into users values('Annabel Ilbert',	'unZOoEy',	'ailbertt@buzzfeed.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'9940 Susan Pass',	1,	'Multi-lateral 4th generation adapter',	'Exclusive mobile analyzer');
insert into users values('Henriette Ouslem',	'egCUpQ',	'houslemu@zimbio.com',	'student',	'0',	'false',	'0',	'',	'female',	'7983 7th Drive',	1,	'Monitored motivating ability',	'Intuitive heuristic matrices');
insert into users values('Kanya Boggish',	'DYwW9HyyWoF',	'kboggishv@ehow.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'329 Donald Pass',	1,	'Expanded actuating projection',	'Multi-lateral global secured line');
insert into users values('Jacquenette Coskerry',	'QLOiYZ0w4M',	'jocoskerryw@rambler.ru',	'student',	'0',	'false',	'0',	'',	'MALE',	'7431 Manufacturers Place',	1,	'Customizable analyzing extranet',	'Expanded fresh-thinking monitoring');
insert into users values('Stormie Strauss',	'fXs59CO',	'sstraussx@princeton.edu',	'student',	'0',	'false',	'0',	'',	'MALE',	'15294 Dottie Court',	1,	'Function-based logistical orchestration',	'Self-enabling user-facing archive');
insert into users values('Lydie Woolvin',	'0XWGGQePm85D',	'lwoolviny@mozilla.org',	'student',	'0',	'false',	'0',	'',	'female',	'9 Dawn Alley',	1,	'Total contextually-based neural-net',	'User-friendly user-facing analyzer');
insert into users values('Grace Dunseath',	'zTLkMhBnQ',	'gdunseathz@mozilla.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'6731 Hermina Drive',	1,	'Customizable bandwidth-monitored standardization',	'Compatible systematic synergy');
insert into users values('Carroll Carlesso',	'eZZrlJYYauTT',	'ccarlesso10@uiuc.edu',	'student',	'0',	'false',	'0',	'',	'female',	'2694 Valley Edge Hill',	1,	'Horizontal multi-tasking leverage',	'Open-source optimal paradigm');
insert into users values('Bidget Conkie',	'JJDrxvPwoP6X',	'bconkie11@xinhuanet.com',	'student',	'0',	'false',	'0',	'',	'female',	'368 Roth Lane',	1,	'Seamless 24 hour analyzer',	'Progressive homogeneous installation');
insert into users values('Barbe Ollerton',	'drTRcLbN3jS',	'bollerton12@plala.or.jp',	'student',	'0',	'false',	'0',	'',	'MALE',	'4560 Logan Parkway',	1,	'Self-enabling zero tolerance structure',	'Optional logistical forecast');
insert into users values('Tiffanie Sygrove',	'j2aZdTZS',	'tsygrove13@dailymotion.com',	'student',	'0',	'false',	'0',	'',	'female',	'529 Granby Street',	1,	'Multi-layered demand-driven adapter',	'User-centric 3rd generation model');
insert into users values('Masha Blasgen',	'Tc1mhX8OlM',	'mblasgen14@hud.gov',	'student',	'0',	'false',	'0',	'',	'MALE',	'000 Vahlen Alley',	1,	'Organic scalable access',	'Horizontal asynchronous firmware');
insert into users values('Caldwell Micallef',	'C7ajZRn',	'cmicallef15@engadget.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'426 Hoard Drive',	1,	'Monitored 3rd generation task-force',	'Streamlined leading edge utilisation');
insert into users values('Jennette McMurrugh',	'lIRIP5d4Zq',	'jmcmurrugh16@drupal.org',	'student',	'0',	'false',	'0',	'',	'female',	'125 Bunting Lane',	1,	'Expanded foreground framework',	'User-friendly contextually-based frame');
insert into users values('Mel Byng',	'1nQitA4PgknT',	'mbyng17@mit.edu',	'student',	'0',	'false',	'0',	'',	'MALE',	'7280 Schiller Avenue',	1,	'Programmable foreground support',	'Networked didactic encoding');
insert into users values('Elnora Branche',	'iwLP8LqAFiHo',	'ebranche18@disqus.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'6090 Del Mar Alley',	1,	'Business-focused radical core',	'Progressive actuating superstructure');
insert into users values('Hughie Ede',	'7KVB9Sd66',	'hede19@nsw.gov.au',	'student',	'0',	'false',	'0',	'',	'MALE',	'640 Sundown Alley',	1,	'Optimized background adapter',	'Re-contextualized fresh-thinking Graphical User Interface');
insert into users values('Marlon Gulvin',	'r3HOMv',	'mgulvin1a@howstuffworks.com',	'student',	'0',	'false',	'0',	'',	'female',	'39463 Sutteridge Trail',	1,	'Multi-tiered coherent capability',	'Devolved holistic complexity');
insert into users values('Matty Harlick',	'4UEhbj2vZ',	'mharlick1b@godaddy.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'961 Pennsylvania Road',	1,	'Realigned object-oriented array',	'User-centric value-added protocol');
insert into users values('Joli MacNeil',	'ILvBXg07RKu7',	'jmacneil1c@dailymotion.com',	'student',	'0',	'false',	'0',	'',	'female',	'320 Maryland Terrace',	1,	'Streamlined multimedia forecast',	'Enhanced user-facing service-desk');
insert into users values('Otes Fanstone',	'nYp2kyjkoT5G',	'ofanstone1d@answers.com',	'student',	'0',	'false',	'0',	'',	'female',	'47511 Golf View Place',	1,	'Decentralized web-enabled data-warehouse',	'Seamless content-based contingency');
insert into users values('Salim Fugere',	'slyju9phv5nG',	'sfugere1e@eventbrite.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'4 Delaware Court',	1,	'Versatile client-server software',	'Devolved real-time groupware');
insert into users values('Ninnetta Blitzer',	'7oaMM0Xequ',	'nblitzer1f@com.com',	'student',	'0',	'false',	'0',	'',	'female',	'958 Meadow Valley Trail',	1,	'Grass-roots contextually-based matrix',	'Grass-roots eco-centric intranet');
insert into users values('Lora Rapelli',	'3BhtRGnMa',	'lrapelli1g@about.me',	'student',	'0',	'false',	'0',	'',	'MALE',	'728 International Place',	1,	'Team-oriented web-enabled capability',	'Optional eco-centric productivity');
insert into users values('Gabriello Hanselmann',	'uw7n05DNoV',	'ghanselmann1h@netscape.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'8418 Ilene Avenue',	1,	'Mandatory hybrid focus group',	'Down-sized bottom-line emulation');
insert into users values('Alla Constant',	'EXKgYar1Eb',	'aconstant1i@cdbaby.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'6 Tony Park',	1,	'Horizontal transitional capability',	'Optimized context-sensitive productivity');
insert into users values('Elayne Gouinlock',	'SnjGqtOD',	'egouinlock1j@about.com',	'student',	'0',	'false',	'0',	'',	'female',	'1098 Sauthoff Park',	1,	'Implemented exuding installation',	'Innovative high-level attitude');
insert into users values('Tamma Menier',	'r416RSoIweI',	'tmenier1k@php.net',	'student',	'0',	'false',	'0',	'',	'MALE',	'8989 West Plaza',	1,	'Profound zero tolerance algorithm',	'Operative bifurcated project');
insert into users values('Teena McClinton',	'tdlmxH',	'tmcclinton1l@devhub.com',	'student',	'0',	'false',	'0',	'',	'female',	'568 Weeping Birch Center',	1,	'Inverse reciprocal utilisation',	'Integrated methodical strategy');
insert into users values('Karyn Howe',	'CR51PA1EA6',	'khowe1m@qq.com',	'student',	'0',	'false',	'0',	'',	'female',	'092 Dawn Lane',	1,	'De-engineered logistical toolset',	'Devolved tertiary flexibility');
insert into users values('Sanson Cunnah',	'gvCXkH',	'scunnah1n@cdbaby.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'2609 Clarendon Point',	1,	'Versatile reciprocal local area network',	'Visionary scalable capacity');
insert into users values('Dennie Challice',	'xGk8DY',	'dchallice1o@arizona.edu',	'student',	'0',	'false',	'0',	'',	'female',	'25 Daystar Court',	1,	'Cloned contextually-based conglomeration',	'Front-line asynchronous groupware');
insert into users values('Chrysler Argue',	'lzprhI',	'cargue1p@biglobe.ne.jp',	'student',	'0',	'false',	'0',	'',	'MALE',	'724 Center Street',	1,	'Virtual client-server success',	'Multi-layered analyzing interface');
insert into users values('Helen Conen',	'dFBIRhxoo3F',	'hconen1q@mashable.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'9 Harbort Parkway',	1,	'Realigned stable process improvement',	'Fully-configurable tangible Graphical User Interface');
insert into users values('Cchaddie Ayris',	't34doxVR',	'cayris1r@csmonitor.com',	'student',	'0',	'false',	'0',	'',	'female',	'2 Goodland Point',	1,	'Re-contextualized multimedia knowledge base',	'Persistent human-resource hierarchy');
insert into users values('Katrinka Booth',	'RfMIu0O',	'kbooth1s@hexun.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'0212 Brown Park',	1,	'Realigned secondary info-mediaries',	'Multi-channelled discrete orchestration');
insert into users values('Oriana Worsnap',	'O3U90BnUCT',	'oworsnap1t@ask.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'999 Hooker Point',	1,	'Front-line full-range pricing structure',	'User-centric well-modulated application');
insert into users values('Georgiana Garbett',	'8rgKJir5UD8U',	'ggarbett1u@craigslist.org',	'student',	'0',	'false',	'0',	'',	'MALE',	'7 Texas Road',	1,	'Multi-channelled multimedia interface',	'Expanded real-time structure');
insert into users values('Dorothea Ciobutaro',	'E5NhZ1wb2e',	'dciobutaro1v@gnu.org',	'student',	'0',	'false',	'0',	'',	'female',	'4 Marquette Alley',	1,	'Future-proofed high-level architecture',	'Stand-alone multimedia budgetary management');
insert into users values('Jorey Kenningham',	'v6XUhg3M',	'jkenningham1w@tinyurl.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'0 Washington Hill',	1,	'Programmable next generation info-mediaries',	'Open-source fault-tolerant flexibility');
insert into users values('Terrel Lundbeck',	'weuHAYlkvc3',	'tlundbeck1x@intel.com',	'student',	'0',	'false',	'0',	'',	'female',	'8 Badeau Drive',	1,	'Operative modular open system',	'Profit-focused actuating infrastructure');
insert into users values('Garret Tolwood',	'7hfwtEXq8zP',	'gtolwood1y@gravatar.com',	'student',	'0',	'false',	'0',	'',	'female',	'548 Hovde Lane',	1,	'Quality-focused upward-trending interface',	'Face to face dedicated system engine');
insert into users values('Astrid Thorald',	'f1nBWvFP',	'athorald1z@cyberchimps.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'34 Scott Place',	1,	'Virtual 6th generation alliance',	'Function-based hybrid Graphical User Interface');
insert into users values('Anne-corinne Draisey',	'4QIod8T4Oo7',	'adraisey20@senate.gov',	'student',	'0',	'false',	'0',	'',	'female',	'68238 Elka Court',	1,	'Stand-alone asymmetric collaboration',	'De-engineered real-time software');
insert into users values('Margaret Chetwin',	'wdkjV0GFtDKA',	'mchetwin21@blogspot.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'6490 Del Mar Lane',	1,	'Inverse secondary alliance',	'Adaptive context-sensitive architecture');
insert into users values('Marian Sneezum',	'q0GmJE',	'msneezum22@walmart.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'0723 Hauk Avenue',	1,	'Versatile actuating encoding',	'Fully-configurable 4th generation ability');
insert into users values('Mel Sullivan',	'fnAw9r4jspO',	'msullivan23@pinterest.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'037 Brown Trail',	1,	'Mandatory directional knowledge base',	'Face to face systematic product');
insert into users values('Roxanna Downton',	'LMlwOcG',	'rdownton24@washingtonpost.com',	'student',	'0',	'false',	'0',	'',	'female',	'35634 Glendale Hill',	1,	'Exclusive bandwidth-monitored product',	'Vision-oriented cohesive info-mediaries');
insert into users values('Tracie McAviy',	'p2A0ryn',	'tmcaviy25@unc.edu',	'student',	'0',	'false',	'0',	'',	'MALE',	'1057 Ruskin Trail',	1,	'Profound system-worthy orchestration',	'Up-sized object-oriented structure');
insert into users values('Herc Banford',	'9D81xk',	'hbanford26@vk.com',	'student',	'0',	'false',	'0',	'',	'female',	'0098 Graedel Park',	1,	'Re-engineered background productivity',	'Reactive 24/7 core');
insert into users values('Brig Di Roberto',	'p4adGzkD19',	'bdi27@reddit.com',	'student',	'0',	'false',	'0',	'',	'female',	'762 Sunnyside Road',	1,	'Fully-configurable explicit hub',	'Re-engineered multi-state collaboration');
insert into users values('Binny Hartshorne',	'7M0PYbCP',	'bhartshorne28@utexas.edu',	'student',	'0',	'false',	'0',	'',	'MALE',	'3 Lukken Terrace',	1,	'Switchable bandwidth-monitored core',	'User-friendly incremental groupware');
insert into users values('Gabie Esposi',	'4kAa9KrB',	'gesposi29@wordpress.com',	'student',	'0',	'false',	'0',	'',	'female',	'05071 Clove Alley',	1,	'Right-sized foreground functionalities',	'Ergonomic 6th generation model');
insert into users values('Farrell Wenham',	'gBoGqMVrtMa',	'fwenham2a@ning.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'59262 Sauthoff Park',	1,	'Down-sized incremental middleware',	'Grass-roots foreground superstructure');
insert into users values('Leora Cazin',	'kNmjgdQs',	'lcazin2b@blogspot.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'54 Ridgeway Parkway',	1,	'Mandatory multimedia throughput',	'Automated uniform paradigm');
insert into users values('Judye Finn',	'USzJ38c2h1a',	'jfinn2c@phpbb.com',	'student',	'0',	'false',	'0',	'',	'female',	'175 South Trail',	1,	'Managed tertiary instruction set',	'Future-proofed multi-tasking parallelism');
insert into users values('Correy Fausch',	'2lUpo7',	'cfausch2d@dion.ne.jp',	'student',	'0',	'false',	'0',	'',	'MALE',	'1241 Springs Avenue',	1,	'Reduced fault-tolerant approach',	'Function-based background collaboration');
insert into users values('Pearle Mitton',	'QhfJtLm',	'pmitton2e@over-blog.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'52 Oneill Drive',	1,	'Innovative dedicated local area network',	'Open-architected 24 hour circuit');
insert into users values('Amaleta Calan',	'orogXxAz',	'acalan2f@msu.edu',	'student',	'0',	'false',	'0',	'',	'MALE',	'8862 Ramsey Junction',	1,	'Managed 6th generation workforce',	'Balanced maximized installation');
insert into users values('Nicoli Cobby',	'dNuSkgHIy9f',	'ncobby2g@ted.com',	'student',	'0',	'false',	'0',	'',	'female',	'56162 Truax Plaza',	1,	'Streamlined well-modulated orchestration',	'Optional well-modulated service-desk');
insert into users values('Mignonne Langthorn',	'QEl0w3BEzUmM',	'mlangthorn2h@barnesandnoble.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'947 Parkside Terrace',	1,	'Open-source client-server encoding',	'Team-oriented 5th generation strategy');
insert into users values('Jed Wanden',	'NsEg2b26W2',	'jwanden2i@xing.com',	'student',	'0',	'false',	'0',	'',	'female',	'71799 Sycamore Court',	1,	'Business-focused modular complexity',	'Ergonomic bandwidth-monitored monitoring');
insert into users values('Dolley Watman',	'fgGG7zTaagg',	'dwatman2j@cisco.com',	'student',	'0',	'false',	'0',	'',	'female',	'729 Grover Avenue',	1,	'Re-engineered multi-tasking function',	'Mandatory well-modulated productivity');
insert into users values('Atlante Tomasello',	'm09FTsWmYe2',	'atomasello2k@admin.ch',	'student',	'0',	'false',	'0',	'',	'MALE',	'7956 Larry Hill',	1,	'Virtual zero administration collaboration',	'Exclusive leading edge model');
insert into users values('Rayner Vasenkov',	'vnzyrqMed0cU',	'rvasenkov2l@instagram.com',	'student',	'0',	'false',	'0',	'',	'female',	'2 Russell Junction',	1,	'Self-enabling exuding emulation',	'Multi-layered grid-enabled open architecture');
insert into users values('Ring Ricciardo',	'eumFLmY8jJI8',	'rricciardo2m@furl.net',	'student',	'0',	'false',	'0',	'',	'MALE',	'6779 Drewry Center',	1,	'Robust empowering hierarchy',	'Streamlined dedicated analyzer');
insert into users values('Claudie Farnin',	'5A91NsyXgP',	'cfarnin2n@nps.gov',	'student',	'0',	'false',	'0',	'',	'MALE',	'172 Blaine Circle',	1,	'Triple-buffered tangible contingency',	'Exclusive eco-centric extranet');
insert into users values('Jamie Emm',	'Nz8wjPtP',	'jemm2o@yahoo.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'9458 Nelson Parkway',	1,	'Synergistic solution-oriented solution',	'Robust local hub');
insert into users values('Elmo Danko',	'0VExU23vvjS',	'edanko2p@youku.com',	'student',	'0',	'false',	'0',	'',	'female',	'4150 Pawling Road',	1,	'Customer-focused composite data-warehouse',	'De-engineered next generation service-desk');
insert into users values('Eva Juste',	'gXPZmdATl',	'ejuste2q@apple.com',	'student',	'0',	'false',	'0',	'',	'MALE',	'7785 Debra Circle',	1,	'Polarised tangible structure',	'Self-enabling modular protocol');
insert into users values('Susana Auld',	'ouDncTFZ5ZY',	'sauld2r@oaic.gov.au',	'student',	'0',	'false',	'0',	'',	'female',	'7495 Kings Crossing',	1,	'Progressive demand-driven monitoring',	'Persistent eco-centric utilisation');
